spring:
    #静态资源处理
    resources:
        #启动默认静态资源处理，默认启动
        add-mappings: true
        cache:
            cachecontrol:
                #缓存响应时间，单位秒
                max-age: 3600
        chain:
            #资源配链启动缓存，默认启动
            cache: true
            #启动资源链，默认禁用
            enabled: true
            #启用压缩资源（gzip，brotil）解析，默认禁用
            compressed: true
            #启用h5应用缓存，默认禁用
            html-application-cache: true
        static-locations: classpath:/static/

    main:
        allow-bean-definition-overriding: true


        #thymeleaf配置
    thymeleaf:
    # 关闭缓存
        cache:false
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
        hikari:
            #连接池名
            pool-name: DateHikariCP
            # 空闲连接存活最大连接时间,默认600000（10min）
            idle-timeout: 180000
            # 最小空闲连接数
            minimum-idle: 5
            # 最大连接数,默认为10
            maximum-pool-size: 10
            # 自动提交从连接池返回的连接
            auto-commit: true
            # 最大存活时间,0表示永久存活，默认180000（30min）
            max-lifetime: 180000
            # 连接超时时间,默认30秒
            connection-timeout: 30000
            # 心跳机制,测试连接是否可用的查询语句
            connection-test-query: SELECT 1
    # redis 配置
    redis:
        host: 192.168.171.3
        port: 6379
        password: 123456
        # 默认数据库
        database: 0
        # 超时时间
        timeout: 5000ms
        lettuce:
            pool:
                # 最大连接数
                max-active: 8
                # 最大连接阻塞等待时间 默认-1
                max-wait: 5000ms
                # 最大空闲连接，默认8
                max-idle: 200
                # 最小空闲连接，默认0
                min-idle: 5
#    web:
#        resources:
#            cache:
#                cachecontrol:
#                    max-age: 3600
#            chain:
#                #资源配链启动缓存，默认启动
#                #启动资源链，默认禁用
#                enabled: true
#                #启用压缩资源（gzip，brotil）解析，默认禁用
#                compressed: true
#                cache: true
#                html-application-cache: true
#            static-locations: classpath:/static/
#            add-mappings: true

#            resources:
#                #启动默认静态资源处理，默认启动
#                chain:
#                    #资源配链启动缓存，默认启动
#
#                    #启用压缩资源（gzip，brotil）解析，默认禁用
#                    #启用h5应用缓存，默认禁用
#                    html-application-cache: true


    #Mybatis-plus配置
    mybatis-plus:
        # 配置mapper.xml映射文件
        mapper-locations: classpath*:/mapper/*Mapper.xml
        # 配置mybatis数据返回类型别名（默认别名是类名）
        type-aliases-package: com.hxr.seckill.pojo

    #mybatis sql打印（方法接口返回的包，不是mapper.xml所在的包）
    logging:
        level:
            com.hxr.seckill.mapper: debug

# rabbitmq配置
    rabbitmq:
        host: 192.168.171.3
        username: guest
        password: guest
        #虚拟主机
        virtual-host: /
        port: 5672
        listener:
          simple:
              #消费者最小数量
              concurrency: 10
              max-concurrency: 10
              #限制消费者每次都只消费一条消息处理完再继续下一条
              prefetch: 1
              #启动时默认启动容器，默认true
              auto-startup: true
              #被拒绝时是否重新进入队列
              default-requeue-rejected: true
        template:
          retry:
              #发布重试默认false
              enabled: true
              # 重试时间，默认1000ms
              initial-interval: 1000ms
              #重试最大次数 默认3次
              max-attempts: 3
              # 重试最大间隔时间
              max-interval: 10000ms
              # 重试最大间隔乘数，如2.0，第一次等10s，第二次20s，第三次40s
              multiplier: 1




